services:
  postgres:
    container_name: weather_postgres
    image: postgres:15.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - weather_db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
  flyway:
    container_name: weather_flyway
    image: flyway/flyway:10.14
    command: -url="jdbc:postgresql://postgres:${DB_PORT}/${POSTGRES_DB}" -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/migration:/flyway/sql
    depends_on:
      - postgres
  server:
    container_name: weather_server
    depends_on:
      - flyway
    build: .
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: ${DB_PORT}
      DB_URL: "jdbc:postgresql://postgres:${DB_PORT}/${POSTGRES_DB}"
      OPEN_WEATHER_KEY: ${OPEN_WEATHER_KEY}
    ports:
      - ${API_PORT}:8080
volumes:
  weather_db_data:

