services:
  postgres:
    image: postgres:15.5
    container_name: weather_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - weather_db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
volumes:
  weather_db_data:

